### PR TITLE
Aglio docs builder

### PR DESCRIPTION
**Pull request by mskyttner**
These changes add a Makefile with two targets or actions:
- build html reference documentation using Aglio (using official Aglio image from Docker Hub)
- build war files using Maven (using official Maven image from Docker Hub)

It also adds the .html reference doc file from "make dox" itself and updates the README.md to link to it and display it properly (will only work after this is merged into the master branch, because uses https://rawgit.com and points to the master branch.

@idali0226 Please see if you can do "make dox" and "make build", if it works please merge!

### CODE REVIEW

**Comment by mskyttner** [comment]
Do you think that .gitignore should include a row that says 
*/target/**
in order to exclude mvn build artifacts from being accidentally added to the repo?

**Comment by mskyttner** [comment]
Oops, the md syntax messed up that row, I try again, should this be in .gitignore:
`*/target/**`
ie "star-slash-target-slash-double-star"

**Comment by idali0226** [comment]
Yes, we can try that.

Ida
On 13 Jun 2016, at 09:49, Markus Skyttner <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you think that .gitignore should include a row that says
/target/*
in order to exclude mvn build artifacts from being accidentally added to the repo?

**Comment by caalle** [comment]
Yes, we should remove all `target`folders. Might be good to add an ignore for `.war` files in general as well?

**Comment by caalle** [comment]
Looking good 👍 https://rawgit.com/DINA-Web/collections-api/aglio-docs-builder/collections-api-reference.html

**Pull request merged**
